# ======================================================================
# @author: Guilherme Vasconcellos <guiyllw@hotmail.com>
# @version: 1.0.0
#
# @description: Compose to start LuizaLabs api
# ======================================================================
version: '3.7'

services:
  api:
    build:
      context: .
    container_name: api
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_CONNECTION: mongodb://mongo:27017/Employee
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:4.0
    container_name: mongo
    ports:
      - 27017:27017
    restart: always
